stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - config/config.yaml
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/components/feature_engineering.py
    deps:
      - src/components/feature_engineering.py
      - data/processed
    outs:
      - data/featured/master_features.parquet

  # NEW: Validation runs BEFORE training
  data_validation:
    cmd: python src/components/data_validation.py
    deps:
      - src/components/data_validation.py
      - data/featured/master_features.parquet
    # No outputs, it just crashes if data is bad

  model_training:
    cmd: PYTHONPATH=. python src/components/model_training.py --config config/config.yaml --params config/params.yaml
    deps:
      - src/components/model_training.py
      - src/components/data_processor.py
      - data/featured/master_features.parquet
    params:
      - training
      - lgbm_params
    outs:
      - data/model/production_pipeline.pkl