training:
  n_splits: 5
  random_state: 42
  target_col: "is_churn"
  unused_cols: 
    - "msno"
    - "is_churn"
    - "bd"
    - "registration_init_time"

lgbm_params:
  objective: "binary"
  metric: "auc"
  n_estimators: 1000
  learning_rate: 0.05
  num_leaves: 31
  max_depth: -1
  min_child_samples: 20
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 0.1
  n_jobs: -1
  verbose: -1